// Copyright 2026 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
// This file is generated by ts-to-schema, do not edit it directly.
// @ts-nocheck
/* cspell:disable */
import type { ICompiledValidator } from "@twin.org/data-core";
import * as external0 from "@twin.org/standards-unece";
import * as external1 from "@twin.org/data-json-ld";
import * as external2 from "@twin.org/blob-storage-models";
import * as external3 from "@twin.org/attestation-models";
const MESSAGES = ["must be string","must be object","must NOT have fewer than 3 items","must be equal to constant","must be array","must be number","must NOT have more than 3 items"];
function createError(instancePath, schemaPath, keyword, params, message) {
return { instancePath, schemaPath, keyword, params, ["message"]: typeof message === "number" ? MESSAGES[message] : message };
}
function pushError(errors, error) {
if (errors === null) {
return [error];
}
errors.push(error);
return errors;
}
/**
 * Compiled validator for the Document schema.
 */
export const CompiledDocument: ICompiledValidator = validate52;
const keyword0 = external0["CompiledUneceDocumentCodeList"];
const keyword1 = external1["CompiledJsonLdNodeObject"];

function validate53(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/documents/DocumentBase" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate53.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data.documentId === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "documentId"},"must have required property '"+"documentId"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data.documentCode === undefined){
const err1 = createError(instancePath,"#/required","required",{missingProperty: "documentCode"},"must have required property '"+"documentCode"+"'");
vErrors = pushError(vErrors, err1);
errors++;
}
if(data.documentId !== undefined){
if(typeof data.documentId !== "string"){
const err2 = createError(instancePath+"/documentId","#/properties/documentId/type","type",{type: "string"},0);
vErrors = pushError(vErrors, err2);
errors++;
}
}
if(data.documentIdFormat !== undefined){
if(typeof data.documentIdFormat !== "string"){
const err3 = createError(instancePath+"/documentIdFormat","#/properties/documentIdFormat/type","type",{type: "string"},0);
vErrors = pushError(vErrors, err3);
errors++;
}
}
if(data.documentCode !== undefined){
if(!(keyword0(data.documentCode, {instancePath:instancePath+"/documentCode",parentData:data,parentDataProperty:"documentCode",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword0.errors : vErrors.concat(keyword0.errors);
errors = vErrors.length;
}
}
if(data.annotationObject !== undefined){
if(!(keyword1(data.annotationObject, {instancePath:instancePath+"/annotationObject",parentData:data,parentDataProperty:"annotationObject",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
errors = vErrors.length;
}
}
}
else {
const err4 = createError(instancePath,"#/type","type",{type: "object"},1);
vErrors = pushError(vErrors, err4);
errors++;
}
validate53.errors = vErrors;
return errors === 0;
}
validate53.evaluated = {"props":{"documentId":true,"documentIdFormat":true,"documentCode":true,"annotationObject":true},"dynamicProps":false,"dynamicItems":false};

const keyword2 = external1["CompiledJsonLdContextDefinitionElement"];

function validate52(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/documents/Document" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate52.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(!(validate53(data, {instancePath,parentData,parentDataProperty,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate53.errors : vErrors.concat(validate53.errors);
errors = vErrors.length;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data["@context"] === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "@context"},"must have required property '"+"@context"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data.type === undefined){
const err1 = createError(instancePath,"#/required","required",{missingProperty: "type"},"must have required property '"+"type"+"'");
vErrors = pushError(vErrors, err1);
errors++;
}
if(data.id === undefined){
const err2 = createError(instancePath,"#/required","required",{missingProperty: "id"},"must have required property '"+"id"+"'");
vErrors = pushError(vErrors, err2);
errors++;
}
if(data.documentRevision === undefined){
const err3 = createError(instancePath,"#/required","required",{missingProperty: "documentRevision"},"must have required property '"+"documentRevision"+"'");
vErrors = pushError(vErrors, err3);
errors++;
}
if(data.blobStorageId === undefined){
const err4 = createError(instancePath,"#/required","required",{missingProperty: "blobStorageId"},"must have required property '"+"blobStorageId"+"'");
vErrors = pushError(vErrors, err4);
errors++;
}
if(data.integrity === undefined){
const err5 = createError(instancePath,"#/required","required",{missingProperty: "integrity"},"must have required property '"+"integrity"+"'");
vErrors = pushError(vErrors, err5);
errors++;
}
if(data.dateCreated === undefined){
const err6 = createError(instancePath,"#/required","required",{missingProperty: "dateCreated"},"must have required property '"+"dateCreated"+"'");
vErrors = pushError(vErrors, err6);
errors++;
}
if(data["@context"] !== undefined){
let data0 = data["@context"];
if(Array.isArray(data0)){
if(data0.length < 3){
const err7 = createError(instancePath+"/@context","#/properties/%40context/minItems","minItems",{limit: 3},2);
vErrors = pushError(vErrors, err7);
errors++;
}
const len0 = data0.length;
if(len0 > 0){
if("https://schema.org" !== data0[0]){
const err8 = createError(instancePath+"/@context/0","#/properties/%40context/prefixItems/0/const","const",{allowedValue: "https://schema.org"},3);
vErrors = pushError(vErrors, err8);
errors++;
}
}
if(len0 > 1){
if("https://schema.twindev.org/documents/" !== data0[1]){
const err9 = createError(instancePath+"/@context/1","#/properties/%40context/prefixItems/1/const","const",{allowedValue: "https://schema.twindev.org/documents/"},3);
vErrors = pushError(vErrors, err9);
errors++;
}
}
if(len0 > 2){
if("https://schema.twindev.org/common/" !== data0[2]){
const err10 = createError(instancePath+"/@context/2","#/properties/%40context/prefixItems/2/const","const",{allowedValue: "https://schema.twindev.org/common/"},3);
vErrors = pushError(vErrors, err10);
errors++;
}
}
const len1 = data0.length;
var valid3 = len1 <= 3;
if(!valid3){
for(let i0=3; i0<len1; i0++){
const _errs7 = errors;
if(!(keyword2(data0[i0], {instancePath:instancePath+"/@context/" + i0,parentData:data0,parentDataProperty:i0,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword2.errors : vErrors.concat(keyword2.errors);
errors = vErrors.length;
}
var valid3 = _errs7 === errors;
}
}
}
else {
const err11 = createError(instancePath+"/@context","#/properties/%40context/type","type",{type: "array"},4);
vErrors = pushError(vErrors, err11);
errors++;
}
}
if(data.type !== undefined){
if("Document" !== data.type){
const err12 = createError(instancePath+"/type","#/properties/type/const","const",{allowedValue: "Document"},3);
vErrors = pushError(vErrors, err12);
errors++;
}
}
if(data.id !== undefined){
if(typeof data.id !== "string"){
const err13 = createError(instancePath+"/id","#/properties/id/type","type",{type: "string"},0);
vErrors = pushError(vErrors, err13);
errors++;
}
}
if(data.documentRevision !== undefined){
let data7 = data.documentRevision;
if(!((typeof data7 == "number") && (isFinite(data7)))){
const err14 = createError(instancePath+"/documentRevision","#/properties/documentRevision/type","type",{type: "number"},5);
vErrors = pushError(vErrors, err14);
errors++;
}
}
if(data.blobStorageId !== undefined){
if(typeof data.blobStorageId !== "string"){
const err15 = createError(instancePath+"/blobStorageId","#/properties/blobStorageId/type","type",{type: "string"},0);
vErrors = pushError(vErrors, err15);
errors++;
}
}
if(data.integrity !== undefined){
if(typeof data.integrity !== "string"){
const err16 = createError(instancePath+"/integrity","#/properties/integrity/type","type",{type: "string"},0);
vErrors = pushError(vErrors, err16);
errors++;
}
}
if(data.attestationId !== undefined){
if(typeof data.attestationId !== "string"){
const err17 = createError(instancePath+"/attestationId","#/properties/attestationId/type","type",{type: "string"},0);
vErrors = pushError(vErrors, err17);
errors++;
}
}
if(data.dateCreated !== undefined){
if(typeof data.dateCreated !== "string"){
const err18 = createError(instancePath+"/dateCreated","#/properties/dateCreated/type","type",{type: "string"},0);
vErrors = pushError(vErrors, err18);
errors++;
}
}
if(data.dateModified !== undefined){
if(typeof data.dateModified !== "string"){
const err19 = createError(instancePath+"/dateModified","#/properties/dateModified/type","type",{type: "string"},0);
vErrors = pushError(vErrors, err19);
errors++;
}
}
if(data.dateDeleted !== undefined){
if(typeof data.dateDeleted !== "string"){
const err20 = createError(instancePath+"/dateDeleted","#/properties/dateDeleted/type","type",{type: "string"},0);
vErrors = pushError(vErrors, err20);
errors++;
}
}
if(data.organizationIdentity !== undefined){
if(typeof data.organizationIdentity !== "string"){
const err21 = createError(instancePath+"/organizationIdentity","#/properties/organizationIdentity/type","type",{type: "string"},0);
vErrors = pushError(vErrors, err21);
errors++;
}
}
if(data.userIdentity !== undefined){
if(typeof data.userIdentity !== "string"){
const err22 = createError(instancePath+"/userIdentity","#/properties/userIdentity/type","type",{type: "string"},0);
vErrors = pushError(vErrors, err22);
errors++;
}
}
}
else {
const err23 = createError(instancePath,"#/type","type",{type: "object"},1);
vErrors = pushError(vErrors, err23);
errors++;
}
validate52.errors = vErrors;
return errors === 0;
}
validate52.evaluated = {"props":{"@context":true,"type":true,"id":true,"documentRevision":true,"blobStorageId":true,"integrity":true,"attestationId":true,"dateCreated":true,"dateModified":true,"dateDeleted":true,"organizationIdentity":true,"userIdentity":true,"documentId":true,"documentIdFormat":true,"documentCode":true,"annotationObject":true},"dynamicProps":false,"dynamicItems":false};

/**
 * Compiled validator for the DocumentAttestation schema.
 */
export const CompiledDocumentAttestation: ICompiledValidator = validate55;

function validate55(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/documents/DocumentAttestation" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate55.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data["@context"] === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "@context"},"must have required property '"+"@context"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data.type === undefined){
const err1 = createError(instancePath,"#/required","required",{missingProperty: "type"},"must have required property '"+"type"+"'");
vErrors = pushError(vErrors, err1);
errors++;
}
if(data.documentId === undefined){
const err2 = createError(instancePath,"#/required","required",{missingProperty: "documentId"},"must have required property '"+"documentId"+"'");
vErrors = pushError(vErrors, err2);
errors++;
}
if(data.documentCode === undefined){
const err3 = createError(instancePath,"#/required","required",{missingProperty: "documentCode"},"must have required property '"+"documentCode"+"'");
vErrors = pushError(vErrors, err3);
errors++;
}
if(data.documentRevision === undefined){
const err4 = createError(instancePath,"#/required","required",{missingProperty: "documentRevision"},"must have required property '"+"documentRevision"+"'");
vErrors = pushError(vErrors, err4);
errors++;
}
if(data.dateCreated === undefined){
const err5 = createError(instancePath,"#/required","required",{missingProperty: "dateCreated"},"must have required property '"+"dateCreated"+"'");
vErrors = pushError(vErrors, err5);
errors++;
}
if(data.integrity === undefined){
const err6 = createError(instancePath,"#/required","required",{missingProperty: "integrity"},"must have required property '"+"integrity"+"'");
vErrors = pushError(vErrors, err6);
errors++;
}
if(data["@context"] !== undefined){
let data0 = data["@context"];
if(Array.isArray(data0)){
if(data0.length > 3){
const err7 = createError(instancePath+"/@context","#/properties/%40context/maxItems","maxItems",{limit: 3},6);
vErrors = pushError(vErrors, err7);
errors++;
}
if(data0.length < 3){
const err8 = createError(instancePath+"/@context","#/properties/%40context/minItems","minItems",{limit: 3},2);
vErrors = pushError(vErrors, err8);
errors++;
}
const len0 = data0.length;
if(len0 > 0){
if("https://schema.org" !== data0[0]){
const err9 = createError(instancePath+"/@context/0","#/properties/%40context/prefixItems/0/const","const",{allowedValue: "https://schema.org"},3);
vErrors = pushError(vErrors, err9);
errors++;
}
}
if(len0 > 1){
if("https://schema.twindev.org/documents/" !== data0[1]){
const err10 = createError(instancePath+"/@context/1","#/properties/%40context/prefixItems/1/const","const",{allowedValue: "https://schema.twindev.org/documents/"},3);
vErrors = pushError(vErrors, err10);
errors++;
}
}
if(len0 > 2){
if("https://schema.twindev.org/common/" !== data0[2]){
const err11 = createError(instancePath+"/@context/2","#/properties/%40context/prefixItems/2/const","const",{allowedValue: "https://schema.twindev.org/common/"},3);
vErrors = pushError(vErrors, err11);
errors++;
}
}
const len1 = data0.length;
if(!(len1 <= 3)){
const err12 = createError(instancePath+"/@context","#/properties/%40context/items","items",{limit: 3},6);
vErrors = pushError(vErrors, err12);
errors++;
}
}
else {
const err13 = createError(instancePath+"/@context","#/properties/%40context/type","type",{type: "array"},4);
vErrors = pushError(vErrors, err13);
errors++;
}
}
if(data.type !== undefined){
if("DocumentAttestation" !== data.type){
const err14 = createError(instancePath+"/type","#/properties/type/const","const",{allowedValue: "DocumentAttestation"},3);
vErrors = pushError(vErrors, err14);
errors++;
}
}
if(data.documentId !== undefined){
if(typeof data.documentId !== "string"){
const err15 = createError(instancePath+"/documentId","#/properties/documentId/type","type",{type: "string"},0);
vErrors = pushError(vErrors, err15);
errors++;
}
}
if(data.documentCode !== undefined){
if(!(keyword0(data.documentCode, {instancePath:instancePath+"/documentCode",parentData:data,parentDataProperty:"documentCode",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword0.errors : vErrors.concat(keyword0.errors);
errors = vErrors.length;
}
}
if(data.documentRevision !== undefined){
let data7 = data.documentRevision;
if(!((typeof data7 == "number") && (isFinite(data7)))){
const err16 = createError(instancePath+"/documentRevision","#/properties/documentRevision/type","type",{type: "number"},5);
vErrors = pushError(vErrors, err16);
errors++;
}
}
if(data.dateCreated !== undefined){
if(typeof data.dateCreated !== "string"){
const err17 = createError(instancePath+"/dateCreated","#/properties/dateCreated/type","type",{type: "string"},0);
vErrors = pushError(vErrors, err17);
errors++;
}
}
if(data.integrity !== undefined){
if(typeof data.integrity !== "string"){
const err18 = createError(instancePath+"/integrity","#/properties/integrity/type","type",{type: "string"},0);
vErrors = pushError(vErrors, err18);
errors++;
}
}
}
else {
const err19 = createError(instancePath,"#/type","type",{type: "object"},1);
vErrors = pushError(vErrors, err19);
errors++;
}
validate55.errors = vErrors;
return errors === 0;
}
validate55.evaluated = {"props":{"@context":true,"type":true,"documentId":true,"documentCode":true,"documentRevision":true,"dateCreated":true,"integrity":true},"dynamicProps":false,"dynamicItems":false};

/**
 * Compiled validator for the DocumentBase schema.
 */
export const CompiledDocumentBase: ICompiledValidator = validate53;

/**
 * Compiled validator for the DocumentHydrated schema.
 */
export const CompiledDocumentHydrated: ICompiledValidator = validate56;
const keyword4 = external2["CompiledBlobStorageEntry"];
const keyword5 = external3["CompiledAttestationInformation"];

function validate56(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/documents/DocumentHydrated" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate56.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(!(validate52(data, {instancePath,parentData,parentDataProperty,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate52.errors : vErrors.concat(validate52.errors);
errors = vErrors.length;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data.blobStorageEntry !== undefined){
if(!(keyword4(data.blobStorageEntry, {instancePath:instancePath+"/blobStorageEntry",parentData:data,parentDataProperty:"blobStorageEntry",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword4.errors : vErrors.concat(keyword4.errors);
errors = vErrors.length;
}
}
if(data.attestationInformation !== undefined){
if(!(keyword5(data.attestationInformation, {instancePath:instancePath+"/attestationInformation",parentData:data,parentDataProperty:"attestationInformation",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword5.errors : vErrors.concat(keyword5.errors);
errors = vErrors.length;
}
}
}
else {
const err0 = createError(instancePath,"#/type","type",{type: "object"},1);
vErrors = pushError(vErrors, err0);
errors++;
}
validate56.errors = vErrors;
return errors === 0;
}
validate56.evaluated = {"props":{"blobStorageEntry":true,"extractedData":true,"attestationInformation":true,"@context":true,"type":true,"id":true,"documentRevision":true,"blobStorageId":true,"integrity":true,"attestationId":true,"dateCreated":true,"dateModified":true,"dateDeleted":true,"organizationIdentity":true,"userIdentity":true,"documentId":true,"documentIdFormat":true,"documentCode":true,"annotationObject":true},"dynamicProps":false,"dynamicItems":false};

/**
 * Compiled validator for the DocumentList schema.
 */
export const CompiledDocumentList: ICompiledValidator = validate58;

function validate58(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/documents/DocumentList" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate58.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data["@context"] === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "@context"},"must have required property '"+"@context"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data.type === undefined){
const err1 = createError(instancePath,"#/required","required",{missingProperty: "type"},"must have required property '"+"type"+"'");
vErrors = pushError(vErrors, err1);
errors++;
}
if(data.itemListElement === undefined){
const err2 = createError(instancePath,"#/required","required",{missingProperty: "itemListElement"},"must have required property '"+"itemListElement"+"'");
vErrors = pushError(vErrors, err2);
errors++;
}
if(data["@context"] !== undefined){
let data0 = data["@context"];
if(Array.isArray(data0)){
if(data0.length < 3){
const err3 = createError(instancePath+"/@context","#/properties/%40context/minItems","minItems",{limit: 3},2);
vErrors = pushError(vErrors, err3);
errors++;
}
const len0 = data0.length;
if(len0 > 0){
if("https://schema.org" !== data0[0]){
const err4 = createError(instancePath+"/@context/0","#/properties/%40context/prefixItems/0/const","const",{allowedValue: "https://schema.org"},3);
vErrors = pushError(vErrors, err4);
errors++;
}
}
if(len0 > 1){
if("https://schema.twindev.org/documents/" !== data0[1]){
const err5 = createError(instancePath+"/@context/1","#/properties/%40context/prefixItems/1/const","const",{allowedValue: "https://schema.twindev.org/documents/"},3);
vErrors = pushError(vErrors, err5);
errors++;
}
}
if(len0 > 2){
if("https://schema.twindev.org/common/" !== data0[2]){
const err6 = createError(instancePath+"/@context/2","#/properties/%40context/prefixItems/2/const","const",{allowedValue: "https://schema.twindev.org/common/"},3);
vErrors = pushError(vErrors, err6);
errors++;
}
}
const len1 = data0.length;
var valid2 = len1 <= 3;
if(!valid2){
for(let i0=3; i0<len1; i0++){
const _errs6 = errors;
if(!(keyword2(data0[i0], {instancePath:instancePath+"/@context/" + i0,parentData:data0,parentDataProperty:i0,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword2.errors : vErrors.concat(keyword2.errors);
errors = vErrors.length;
}
var valid2 = _errs6 === errors;
}
}
}
else {
const err7 = createError(instancePath+"/@context","#/properties/%40context/type","type",{type: "array"},4);
vErrors = pushError(vErrors, err7);
errors++;
}
}
if(data.type !== undefined){
if("ItemList" !== data.type){
const err8 = createError(instancePath+"/type","#/properties/type/const","const",{allowedValue: "ItemList"},3);
vErrors = pushError(vErrors, err8);
errors++;
}
}
if(data.itemListElement !== undefined){
let data6 = data.itemListElement;
if(Array.isArray(data6)){
const len2 = data6.length;
for(let i1=0; i1<len2; i1++){
if(!(validate56(data6[i1], {instancePath:instancePath+"/itemListElement/" + i1,parentData:data6,parentDataProperty:i1,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate56.errors : vErrors.concat(validate56.errors);
errors = vErrors.length;
}
}
}
else {
const err9 = createError(instancePath+"/itemListElement","#/properties/itemListElement/type","type",{type: "array"},4);
vErrors = pushError(vErrors, err9);
errors++;
}
}
if(data.edges !== undefined){
let data8 = data.edges;
if(Array.isArray(data8)){
const len3 = data8.length;
for(let i2=0; i2<len3; i2++){
if(typeof data8[i2] !== "string"){
const err10 = createError(instancePath+"/edges/" + i2,"#/properties/edges/items/type","type",{type: "string"},0);
vErrors = pushError(vErrors, err10);
errors++;
}
}
}
else {
const err11 = createError(instancePath+"/edges","#/properties/edges/type","type",{type: "array"},4);
vErrors = pushError(vErrors, err11);
errors++;
}
}
}
else {
const err12 = createError(instancePath,"#/type","type",{type: "object"},1);
vErrors = pushError(vErrors, err12);
errors++;
}
validate58.errors = vErrors;
return errors === 0;
}
validate58.evaluated = {"props":{"@context":true,"type":true,"itemListElement":true,"edges":true},"dynamicProps":false,"dynamicItems":false};

